"""Shared helpers: score-to-label mapping and timestamp formatting."""

from datetime import datetime, timezone

# Score thresholds (high -> low) mapped to (attribution, transparency label).
# A 0-1 score is "AI-likeness": 0 = human, 1 = AI. The first threshold the
# score meets, scanning top to bottom, wins.
SCORE_LABELS = [
    (0.80, "ai_generated", "⚠️ AI-GENERATED CONTENT DETECTED"),
    (0.60, "likely_ai", "⚡ AI-GENERATED CONTENT LIKELY"),
    (0.40, "uncertain", "🔍 UNCERTAIN - Human Review Recommended"),
    (0.20, "likely_human", "📝 LIKELY HUMAN-WRITTEN CONTENT"),
    (0.00, "human_written", "✅ HUMAN-WRITTEN CONTENT CONFIRMED"),
]


def classify_score(score):
    """Map a 0-1 AI-likeness score to its (attribution, label) pair."""
    for threshold, attribution, label in SCORE_LABELS:
        if score >= threshold:
            return attribution, label
    # Scores are clamped to 0-1 upstream, so the final row always matches;
    # this is a defensive fallback for an out-of-range score.
    return SCORE_LABELS[-1][1], SCORE_LABELS[-1][2]


def predict_attribution(combined_score):
    """Standardized PREDICTION label, kept distinct from the transparency variant.

    Returns exactly one of: 'ai_generated', 'uncertain', 'human_written'.

    These three thresholds collapse the finer 5-tier classify_score bands so
    that `attribution` is always a clean prediction enum (never a 'likely_*'
    transparency value):
        combined >= 0.60          -> ai_generated   (likely_ai + ai_generated)
        0.40 <= combined < 0.60   -> uncertain
        combined <  0.40          -> human_written  (likely_human + human_written)

    This does not change the detection pipeline or confidence: it only maps the
    existing combined_score to a standardized output label.
    """
    if combined_score >= 0.60:
        return "ai_generated"
    if combined_score >= 0.40:
        return "uncertain"
    return "human_written"


def iso_timestamp():
    """Return the current UTC time as an ISO-8601 string ending in 'Z'."""
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


# --- Milestone 4: ensemble combination of the two detection signals ----------
# Weights come from planning.md ("weighted average (Groq: 60%, Stylometric:
# 40%)" and "raw_score = (groq_score x 0.6) + (stylometric_score x 0.4)").
# The planning document takes precedence over the 70/30 default. Groq is
# weighted higher because it captures semantic meaning; the stylometric signal
# is purely structural and so contributes less.
GROQ_WEIGHT = 0.60
STYLOMETRIC_WEIGHT = 0.40


def combine_scores(groq_score, stylometric_score):
    """Combine the two independent signal scores into one 0-1 AI-likeness score.

    combined = 0.60 * groq_score + 0.40 * stylometric_score
    """
    return GROQ_WEIGHT * groq_score + STYLOMETRIC_WEIGHT * stylometric_score


def compute_confidence(combined_score):
    """Confidence in the prediction (0-1), as a deterministic function.

    Confidence rises as the combined score moves away from 0.5 (a clear
    human or AI signal) and falls to 0 at exactly 0.5 (maximal uncertainty):

        confidence = 2 * |combined_score - 0.5|

    Note: planning.md discusses a richer signal-agreement calibration, but it
    uses the calibrated score itself as the "confidence" percentage, which does
    not match the distance-from-0.5 behavior required here. We therefore follow
    the explicit distance-based definition for this metric.
    """
    return max(0.0, min(1.0, 2 * abs(combined_score - 0.5)))


# --- Milestone 5: transparency label variants -------------------------------
# planning.md's Label Generator defines three user-facing transparency labels:
#   "Likely AI-Generated", "Uncertain - Human Review Recommended",
#   "Likely Human-Written".
#
# This label is PURELY EXPLANATORY. The variant is derived from the existing
# (unchanged) 5-tier `attribution` collapsed into these three buckets, so the
# transparency label can never contradict the prediction. The Milestone 4
# confidence score is interpolated into the text, so the wording shown to the
# user varies according to how confident the system is. Neither the prediction
# nor the confidence value is changed here.
_TRANSPARENCY_BUCKETS = {
    "ai_generated": "likely_ai",
    "likely_ai": "likely_ai",
    "uncertain": "uncertain",
    "likely_human": "likely_human",
    "human_written": "likely_human",
}

_TRANSPARENCY_TEMPLATES = {
    "likely_ai": (
        "Likely AI-Generated — our analysis suggests this content was "
        "generated by AI. (confidence: {pct}%)"
    ),
    "uncertain": (
        "Uncertain - Human Review Recommended — we could not confidently "
        "determine attribution. (confidence: {pct}%)"
    ),
    "likely_human": (
        "Likely Human-Written — our analysis suggests this content was "
        "written by a human. (confidence: {pct}%)"
    ),
}


def transparency_label(attribution, confidence, is_verified=False):
    """Build the user-facing transparency label.

    Args:
        attribution: the unchanged prediction (one of the 5-tier values).
        confidence: the Milestone 4 confidence score (0-1).
        is_verified: whether the creator holds an active Verified Human
            credential. When True the label gets a 👤 badge and a note. This is
            purely a display annotation — it does NOT change the prediction,
            score, or confidence.

    Returns:
        (variant, text) where variant is one of 'likely_ai', 'uncertain',
        'likely_human' and text is the explanatory message with the confidence
        percentage interpolated.
    """
    variant = _TRANSPARENCY_BUCKETS.get(attribution, "uncertain")
    pct = round(confidence * 100)
    text = _TRANSPARENCY_TEMPLATES[variant].format(pct=pct)
    if is_verified:
        text = "👤 " + text + " This creator has a Verified Human credential."
    return variant, text
